bcgov/von

EstablishingAVerifiedOrg.md

Pronoun edits

---

docs/_data/navigation.yml
docs/_getting_started/01-quick-start-guide.md
docs/_getting_started/02-von-overview.md
docs/_getting_started/03-von-participants.md
docs/_getting_started/04-running-tob-instance.md
docs/_getting_started/05-issuing-permits-licences.md
docs/_getting_started/06-contributing.md
docs/_getting_started/07-von-network.md
docs/_getting_started/08-von-agent.md
docs/_getting_started/09-von-x-permitify.md
docs/_getting_started/10-von-image.md
docs/_getting_started/11-theorgbook.md
docs/_getting_started/12-did-auth.md
docs/_getting_started/13-von-glossary.md
docs/_getting_started/14-documentation.md
docs/_getting_started/15-bc-architecture.md
docs/_getting_started/16-sri-architecture.md
docs/_getting_started/17-ontario-architecture.md
docs/_how_to/contributing.md
docs/_how_to/generating-code-docs.md
docs/_how_to/tracking-issues.md
docs/_how_to/updating-docs.md
docs/_includes/footer.html
docs/_includes/sidebar.html
docs/_pages/about.md
docs/_pages/terms.md
docs/_sass/minimal-mistakes/_footer.scss
docs/_sass/minimal-mistakes/_masthead.scss
docs/_sass/minimal-mistakes/_navigation.scss
docs/_sass/minimal-mistakes/_sidebar.scss

Hi @swcurran,
Thanks for your patience! I made a few changes to our sitewide navigation to use the new brand colours and I've redesigned the footer so that it's easier to see the site's content from any part of the site. 
Here's a list of the changes that I've made:
- I made two versions for the site nav—one is white, and one is blue. I had initially designed it to be blue (to match the homepage) but I wasn't sure if I liked it. Let me know which one you guys prefer.
*Option 1*
*Option 2*
- The footer is modified from `_data/navigation.yml` to stay consistent with how the site's navigation system works. I think this makes it easier to summarize the site's content and see what's available on the site, but feel free to modify the links as you see fit. 
*Desktop*
*Mobile*
- I've modified …

Modified site-wide nav to use VON branding

---

docs/_config.yml

Change baseurl

---

docs/_config.yml

Revert change for baseurl

---

docs/_config.yml
docs/_data/authors.yml
docs/_data/hero.yml
docs/_drafts/post-draft.md
docs/_getting_started/01-quick-start-guide.md
docs/_includes/footer/custom.html
docs/_pages/home.md
docs/_sass/minimal-mistakes/_footer.scss
docs/_sass/minimal-mistakes/_masthead.scss
docs/_sass/minimal-mistakes/skins/_von.scss

Fixing paths to work locally and with github pages

---

docs/README.md

#129 Readme for content providers

---

docs/_drafts/cwu-awarded.md
docs/_drafts/whats-next-theorgbook.md

Add documents from Ghost site as drafts

---

docs/_pages/about.md

Updated the About page

---

docs/_getting_started/ontario-architecture.md

Fixes to pathes of the images

---

docs/_getting_started/ontario-architecture.md

Another update to how images are referenced

---

docs/_config.yml

Limited google analytics

---

docs/_getting_started/get-started.md

Fix links on get started page

---

docs/_getting_started/ontario-architecture.md

Testing image path on prod

---

docs/_getting_started/ontario-architecture.md

File path cleanup

---

docs/_pages/clicky-things.md

minor updates

---

docs/_pages/clicky-things.md

more tweaks

---

docs/_pages/clicky-things.md

update URLs for BCovrin ledgers

---

docs/_pages/home.md

update home page

---

docs/_pages/home.md

add angle bracket

---

docs/_pages/home.md

fix anchor

---

docs/_getting_started/dev-quick-start-guide.md
docs/_getting_started/get-started.md
docs/_pages/clicky-things.md
docs/_pages/home.md

Change from permitify to dFlow

---

docs/_config.yml
docs/_includes/analytics.html
docs/_layouts/default.html
docs/_pages/terms.md

Signed-off-by: Emiliano Suñé <emiliano.sune@gmail.com>

Remove Google Analytics and add Fathom Analytics.

---

docs/_includes/analytics.html

Signed-off-by: Emiliano Suñé <emiliano.sune@gmail.com>

Add matomo tracking code.

---

README.md
docs/_config.yml
docs/_pages/clicky-things.md

Minor updates; clicky things updates to reflect lastest info

---

docs/_config.yml
docs/_data/navigation.yml
docs/_getting_started/ontario-architecture.md
docs/_how_to/adding-news-articles.md
docs/_how_to/contributing.md
docs/_pages/collection-archive.html
docs/_pages/news-archive.md
docs/_pages/sitemap.md
docs/_pages/tag-archive.md

Enabling news and adding an article on adding news

---

docs/_news/2019-04-01-VON-team-in-news-Linux-Foundation-blogpost.md

Signed-off-by: carolhoward <choward@cloudcompass.ca>

News article about VON & Linux Foundation Blog Post

---

docs/_data/navigation.yml
docs/_how_to/chat.md
docs/_how_to/contributing.md
docs/_pages/about.md
docs/_pages/clicky-things.md

Information on joining the pathfinder rocketchat

---

docs/_news/2019-04-03-Code-with-us-winner-announced.md

Signed-off-by: Carol Howard <choward@cloudcompass.ca>

news article re code with us winner

---

docs/_news/2019-04-03-Code-with-us-winner-announced.md
docs/_pages/news-archive.md

Updated ordering of news articles on news page

---

docs/_news/2019-03-28-AgentBook-Demo.md
docs/_news/2019-03-28-HLIndyBootcampVancouver.md
docs/_news/2019-04-25-IIWBook-Demo.md

Article about IIWBook Demo

---

docs/_how_to/IIW Demo Guide.md

updates to intro paragraph

---

docs/_how_to/IIW Demo Guide.md

Signed-off-by: Carol Howard <choward@cloudcompass.ca>

Fix a link and the numbering

---

docs/_how_to/IIW Demo Guide.md

Stress that it is more than just identity

---

docs/_how_to/IIW Demo Guide.md

Added references to the document

---

docs/_how_to/IIW Demo Guide.md

Tweaking things/typos

---

docs/_drafts/2019-05-03-IIW28-A-Verifying-Success.md

Hide article until pictures rotated

---

docs/_news/2019-05-03-IIW28-A-Verifying-Success.md

Signed-off-by: Carol Howard <choward@cloudcompass.ca>

File reference change

---

docs/_news/2019-05-03-IIW28-A-Verifying-Success.md

Playing with images - just to see

---

docs/_how_to/chat.md

Update the documentation for joining rocketchat

---

docs/_news/2019-07-24-BC-Gov-MOU-Mobile-Agent.md

MOU Announcement in news

---

docs/_how_to/IIW Demo Guide.md

Add instructions for changing the network to BCovrin Test

---

docs/_how_to/IIW Demo Guide.md

Instructions updates for new Streetcred agent and links to RFCs

---

docs/_pages/about.md

Spelling on about

---

docs/_pages/clicky-things.md

Infominer.id is depreciated + working to better highlight BCGov @ decentralized-id.com

new url HGF 2018 govt deploy indy presentation
